import os

# Celery
BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://redis:6379')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://redis:6379')
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# Open AI key
OPENAI_API_KEY = os.getenv('OPEN_AI_KEY')
OPENAI_AI_API_VERSION = os.getenv('OPENAI_AI_API_VERSION')
OPENAI_AI_MODEL_NAME = os.getenv('OPENAI_AI_MODEL_NAME')

# Pinecone
PINECONE_API_KEY = os.getenv('PINECONE_API_KEY')
PINECONE_ENVIRONMENT = os.getenv('PINECONE_ENVIRONMENT')
PINECONE_INDEX_NAME = os.getenv('PINECONE_INDEX_NAME')
PINECONE_NAMESPACE_NAME = os.getenv('PINECONE_NAMESPACE_NAME')

# Admin Site Config
ADMIN_SITE_HEADER = os.getenv('ADMIN_SITE_HEADER')
ADMIN_SITE_TITLE = os.getenv('ADMIN_SITE_TITLE')
ADMIN_SITE_INDEX = os.getenv('ADMIN_SITE_INDEX')

# API Panel

API_TITLE = os.getenv('API_TITLE', "Title")
API_DESCRIPTION = os.getenv('API_DESCRIPTION', "Documentation")
API_DEFAULT_VERSION = os.getenv('API_DEFAULT_VERSION', "v1")

# OAuth2 settings
APPLICATION_NAME = os.getenv('APPLICATION_NAME', 'chatbot')
